version: '3'

services:
  app: #name of your service
    build: ./ # specify the directory of the Dockerfile
    restart: always
    container_name: opengist
    ports:
      - "127.0.0.1:3012:3000" #specify ports forwarding
    depends_on:
      - open-gist-database

  open-gist-database: # name of the service
    container_name: opengist-db
    image: mongo
    volumes:
      - ~/OpenGistData:/data/db
